### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.Engine' in file /lib/JSExtract.py

### ISSUE THREAD

**Issue by offsecdawn** [machinexa2/Nemesis#1]
When I tried to run JScanner, I am getting below error. 
**$ python3 JScanner.py -u https://****.js**
Traceback (most recent call last):
  File "JScanner.py", line 6, in <module>
    from lib.JSExtract import JSExtract
  File "/opt/tools/javascript_enumeration/JScanner/lib/JSExtract.py", line 6, in <module>
    from lib.Engine import Engine
**ModuleNotFoundError: No module named 'lib.Engine'**

python version in my system:
**Python 3.8.5**

can you please help me with this?

**Comment by machinexa2** [comment]
@offsecdawn can you reinstall. It seems to work for me

**Comment by machinexa2** [comment]
@offsecdawn download and try again

**Comment by machinexa2** [comment]
try both git clone or download packages. You can try binary too

**Comment by machinexa2** [comment]
Also, now JScanner is changed to Nemesis. Use `pip install nemesis-scan`
