### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'nimble'

### ISSUE THREAD

**Issue by ratnadip1998** [machinexa2/Nemesis#3]
Not working...

I downloaded all requirements but still getting kinda error...

I tried both git clone & released one also getting same error.
![JScanner](https://user-images.githubusercontent.com/40835957/121685302-653cd200-cadd-11eb-9d67-9cd43bcca1a0.PNG)

**Comment by machinexa2** [comment]
`apt install nimble`

**Comment by machinexa2** [comment]
@ratnadip1998 I have too additional refactoring but I dont have time now. Its not best at this stage but will surely improve

**Comment by machinexa2** [comment]
Also use python3 not python2

**Comment by machinexa2** [comment]
I have removed faster_than_requests so it should work now.
